### ISSUE TITLE
Do you implement some serializable consistency tricks like range lock?

### ISSUE THREAD

**Issue by Handora** [jasonleaster/simple-db#9]
There is the case that you insert one tuple and all old pages are full, so you need to insert a new page. While you should lock it in some case that scan read occurred simultaneously. So you can avoid a case called unrepeatable read. It is said in lab4, while no test tests it.Would you like to further implement it?

The second question is whether you pass the Transaction system test. I read your lock manager, and find you are not implemented use timeout. I read the test, and I find it is somehow difficult for the timeout to implement. I implement it use a large amount of code for the timeout to pass it and sometimes felt confused.

**Comment by jasonleaster** [comment]
Welcome for your question.

For your first quesiton
I have not implement the range lock at this moment, but I am working on it.  My final target is to help simple-db to run as a standalone server which will accept http connection and works like a "real-DB". Aha ... that's final... that may be a long time...
But I think that I will implement the range lock for concurrent manager in the coming 1 or 2 month but not now.

I am working on writing some articles for what I have got in 6.830. I would like to share it with others.

About the second point, 
I passed most unit test and system test except the BTree related. Lab 1 2 3 4 6  done. Yeh... I also have not implement the time-out mechanism for transaction manager. But that's simple don't be worry. In my strategy, you should treat your transaction like a thread and try to build a `RunningThreadManager` class to monitor those running transaction. That manager will help you manage the lifecycle of your thread.

Good luck.
